name: CI configuration

on:
  workflow_call:
    outputs:
      config:
        value: ${{ jobs.config.outputs.config }}
      latest_python:
        value: ${{ jobs.config.outputs.latest_python }}

jobs:
  config:
    name: Read configuration
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.result }}
      latest_python: ${{ steps.python.outputs.latest_python }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Read configuration from JSON
        uses: actions/github-script@v6
        id: config
        with:
          script: |
            return require("./.github/workflows/config.json")
      - name: Get latest Python version
        id: python
        run: |
          python_version=$(echo '${{ steps.config.outputs.result }}' | jq -cr '.python_version|last')
          echo "latest_python=$python_version" >> $GITHUB_OUTPUT
