name: Build binary files

on:
  workflow_call:
    inputs:
      package-version:
        required: True
        type: string
      binary-files:
        required: True
        type: string

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: data/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          tags: nuitka-builder
          outputs: type=docker,dest=nuitka-builder.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v3
        with:
          name: nuitka-builder
          path: nuitka-builder.tar

  build-binary-file:
    name: Build ${{ matrix.binary-file }} binary file
    runs-on: ubuntu-latest

    needs:
      - build-docker-image

    strategy:
      matrix:
        binary-file: ${{ fromJson(inputs.binary-files) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: nuitka-builder

      - name: Build binary files
        run: ./reusable-workflows/.github/scripts/build-binary-files.sh

      - name: Compress binary files
        run: ./reusable-workflows/.github/scripts/compress-binary-files.sh

      - name: Upload compressed binary file
        uses: actions/upload-artifact@v3
        with:
          name: binary-files
          path: ${{ matrix.binary-file }}-${{ inputs.package-version }}-arm64.tar.gz
