name: Build OPKG package

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string
      package-name:
        required: True
        type: string
      package-version:
        required: True
        type: string
      opkg-package:
        type: string

jobs:
  build-opkg-package:
    name: Build OPKG package
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.latest-python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.latest-python-version }}

      - name: Download binary files
        uses: actions/download-artifact@v3
        with:
          name: binary-files
          path: binary-files

      - name: Set up OPKG package
        run: |
          mkdir -pv control

          (
            echo "Package: ${{ inputs.package-name }}"
            echo "Version: ${{ inputs.package-version }}"
            echo "Architecture: aarch64"
            echo "Maintainer: $(python setup.py --author)"
            echo "Source: $(python setup.py --url)"
            echo "Description: $(python setup.py --description)"
            echo "License: $(python setup.py --license)"
          ) > control/control

          echo "2.0" > debian-binary

      - name: Added data from repository
        if: inputs.opkg-package != ''
        run: |
          mkdir -pv data/usr/local/
          cp -rv ${{ inputs.opkg-package }}/* data/usr/local/

      - name: Added binary data
        run: |
          mkdir -pv data/usr/local/bin/
          for f in binary-files/*.tar.gz; do tar xzfv "${f}" -C binary-files; done
          rm -fv binary-files/*.tar.gz
          cp -v binary-files/* data/usr/local/bin/

      - name: Build OPKG package
        run: |
          tar -C control -czvf control.tar.gz .
          tar -C data -czvf data.tar.gz .

          mkdir -pv opkg-package
          tar czvf \
            opkg-package/${{ inputs.package-name }}_${{ inputs.package-version }}_aarch64.ipk \
            control.tar.gz data.tar.gz debian-binary

      - name: Upload OPKG package
        uses: actions/upload-artifact@v3
        with:
          name: opkg-package
          path: opkg-package
