name: Code analyse

on:
  workflow_call:
    inputs:
      python-versions:
        required: True
        type: string

jobs:
  code-analyse:
    name: Code analyse using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install requirements
        run: |
          pip install .[lint,format]

      - name: Check code format with black
        run: |
          black --version
          black --diff --check $(git ls-files '*.py')

      - name: Lint with mypy
        run: mypy $(git ls-files '*.py')

      - name: Lint with ruff
        run: |
          ruff --version
          ruff $(git ls-files '*.py')

      - name: Lint with pylint
        run: |
          pylint --version
          pylint $(git ls-files '*.py')

      - name: Lint with yamllint
        run: |
          yamllint --version
          yamllint $(git ls-files '*.yaml') $(git ls-files '*.yml')
