name: Code analyse

on:
  workflow_call:
    inputs:
      python-versions:
        required: True
        type: string

jobs:
  code-analyse:
    name: Code analyse using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check out reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Lint
        run: ./reusable-workflows/.github/scripts/lint.sh
