name: Coverage

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string

jobs:
  generate-coverage-badge:
    name: Generate coverage badge
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out reusable workflow repository
        uses: actions/checkout@v4
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.latest-python-version }}
          cache: pip

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-python-${{ inputs.latest-python-version }}

      - name: Create coverage badge
        run: ./reusable-workflows/.github/scripts/create-coverage-badge.sh

      - name: Verify coverage badge changed
        uses: tj-actions/verify-changed-files@v16
        id: changed-files
        with:
          files: coverage.svg

      - name: Commit coverage badge
        if: steps.changed-files.outputs.files_changed == 'true'
        run: ./reusable-workflows/.github/scripts/commit-coverage-badge.sh

      - name: Push changes
        if: steps.changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
