name: Parameters

on:
  workflow_call:
    inputs:
      json:
        required: True
        type: string
    outputs:
      python-versions:
        value: ${{ jobs.set-up-parameters.outputs.python-versions }}
      latest-python-version:
        value: ${{ jobs.set-up-parameters.outputs.latest-python-version }}
      package-name:
        value: ${{ jobs.set-up-parameters.outputs.package-name}}
      package-version:
        value: ${{ jobs.set-up-parameters.outputs.package-version }}
      package-maintainer:
        value: ${{ jobs.set-up-parameters.outputs.package-maintainer }}
      package-source-url:
        value: ${{ jobs.set-up-parameters.outputs.package-source-url }}
      package-description:
        value: ${{ jobs.set-up-parameters.outputs.package-description }}
      package-license:
        value: ${{ jobs.set-up-parameters.outputs.package-license }}
      binary-files:
        value: ${{ jobs.set-up-parameters.outputs.binary-files }}
      is-dev-version:
        value: ${{ jobs.set-up-parameters.outputs.is-dev-version }}

jobs:
  set-up-parameters:
    name: Set up parameters
    runs-on: ubuntu-latest

    outputs:
      python-versions: ${{ steps.python.outputs.python-versions }}
      latest-python-version: ${{ steps.python.outputs.latest-python-version }}
      package-name: ${{ steps.params.outputs.package-name }}
      package-version: ${{ steps.params.outputs.package-version }}
      package-maintainer: ${{ steps.params.outputs.package-maintainer }}
      package-source-url: ${{ steps.params.outputs.source-url }}
      package-description: ${{ steps.params.outputs.package-description }}
      package-license: ${{ steps.params.outputs.package-license }}
      binary-files: ${{ steps.params.outputs.binary-files }}
      is-dev-version: ${{ steps.params.outputs.is-dev-version == 'True' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out reusable workflow repository
        uses: actions/checkout@v4
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Get Python version
        id: python
        run: |
          ./reusable-workflows/.github/scripts/get-python-version.py \
            "${{ inputs.json }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python.outputs.latest-python-version }}
          cache: pip

      - name: Install requirements
        run: |
          pip install .
          pip install toml
          pip list

      - name: Generate 'params'
        id: params
        run: |
          ./reusable-workflows/.github/scripts/generate-params.py \
            "${{ inputs.json }}"
