name: Parameters

on:
  workflow_call:
    inputs:
      json:
        required: True
        type: string
    outputs:
      python-versions:
        value: ${{ jobs.set-up-parameters.outputs.python-versions }}
      latest-python-version:
        value: ${{ jobs.set-up-parameters.outputs.latest-python-version }}
      package-name:
        value: ${{ jobs.set-up-parameters.outputs.package-name}}
      package-version:
        value: ${{ jobs.set-up-parameters.outputs.package-version }}
      binary-files:
        value: ${{ jobs.set-up-parameters.outputs.binary-files }}
      version-dev:
        value: ${{ jobs.set-up-parameters.outputs.version-dev }}

jobs:
  set-up-parameters:
    name: Set up parameters
    runs-on: ubuntu-latest

    outputs:
      python-versions: ${{ steps.params.outputs.python-versions }}
      latest-python-version: ${{ steps.params.outputs.latest-python-version }}
      package-name: ${{ steps.params.outputs.package-name }}
      package-alternate-name: ${{ steps.params.outputs.package-alternate-name }}
      package-version: ${{ steps.params.outputs.package-version }}
      binary-files: ${{ steps.params.outputs.binary-files }}
      version-dev: ${{ steps.params.outputs.version-dev == 'True' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check out reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Generate 'params'
        id: params
        run: |
          ls -la reusable-workflows
          ./.github/scripts/generate-params.py
