name: Parameters

on:
  workflow_call:
    inputs:
      python-version:
        required: True
        default: 3.8 3.9 3.10 3.11
        type: string
    outputs:
      python-version:
        value: ${{ jobs.set-up-parameters.outputs.python-version }}
      latest-python-version:
        value: ${{ jobs.set-up-parameters.outputs.latest-python-version }}
      package-name:
        value: ${{ jobs.set-up-parameters.outputs.package-name}}
      package-version:
        value: ${{ jobs.set-up-parameters.outputs.package-version }}

jobs:
  set-up-parameters:
    name: Set up parameters
    runs-on: ubuntu-latest

    outputs:
      python-version: ${{ steps.params.outputs.python-version }}
      latest-python-version: ${{ steps.params.outputs.latest-python-version }}
      package-name: ${{ steps.params.outputs.package-name }}
      package-alternate-name: ${{ steps.params.outputs.package-alternate-name }}
      package-version: ${{ steps.params.outputs.package-version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Test
        run: |
          echo "${{ github.ref_name }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref_type }}"

      - name: Generate 'params'
        id: params
        shell: sh
        run: python scripts/generate_params.py
