name: Prepare build

on:
  workflow_call:
    outputs:
      package_name:
        value: ${{ jobs.prepare_build.outputs.package_name }}
      package_alternate_name:
        value: ${{ jobs.prepare_build.outputs.package_alternate_name }}
      package_version:
        value: ${{ jobs.prepare_build.outputs.package_version }}

jobs:
  prepare_build:
    name: Prepare build
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.package_vars.outputs.package_name }}
      package_alternate_name: ${{ steps.package_vars.outputs.package_alternate_name }}
      package_version: ${{ steps.package_vars.outputs.package_version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set package variables
        id: package_vars
        run: |
          version_dev=$(echo "${{ github.ref_name }}" | cut -d '.' -f 3)

          echo "package_name=$(python setup.py --name)" >> $GITHUB_OUTPUT
          echo "package_alternate_name=$(echo $(python setup.py --name) | sed -r 's/-/_/g')" >> $GITHUB_OUTPUT
          echo "package_version=$(python setup.py --version)" >> $GITHUB_OUTPUT

          if [ "${version_dev}" == "" ]; then
            echo "package_version=$(python setup.py --version)" >> $GITHUB_OUTPUT
          else
            echo "package_version=$(python setup.py --version).dev${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
