name: Publish

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: True

jobs:
  publish-on-pypi:
    name: Publish on PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Download package files
        uses: actions/download-artifact@v3
        with:
          name: python-package

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: .
