name: Publish on FTP

on:
  workflow_call:
    inputs:
      ftp-hostname:
        required: True
        type: string
      ftp-port:
        required: True
        type: string
      ftp-username:
        required: True
        type: string
      ftp-publish-path:
        required: True
        type: string
      is-dev-version:
        type: string
        default: 'false'
    secrets:
      FTP_PASSWORD:
        required: True

jobs:
  publish-on-ftp:
    name: Publish on FTP
    runs-on: ubuntu-latest
    steps:
      - name: Check out reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Download files
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Publish on FTP
        run: ./reusable-workflows/.github/scripts/publish-on-ftp.sh
