name: Publish on PyPi

on:
  workflow_call:

jobs:
  prepare_publish:
    name: Prepare publish
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.package_vars.outputs.package_name }}
      package_alternate_name: ${{ steps.package_vars.outputs.package_alternate_name }}
      package_version: ${{ steps.package_vars.outputs.package_version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set package variables
        id: package_vars
        run: |
          echo "package_name=$(python setup.py --name)" >> $GITHUB_OUTPUT
          echo "package_alternate_name=$(echo $(python setup.py --name) | sed -r 's/-/_/g')" >> $GITHUB_OUTPUT
          echo "package_version=$(python setup.py --version)" >> $GITHUB_OUTPUT

  release:
    name: Publish
    needs:
      - prepare_publish
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v3
      - name: Move python packages to /dist
        # yamllint disable rule:line-length
        run: |
          mkdir -pv dist
          mv -v ${{ needs.prepare_publish.outputs.package_name }}-${{ needs.prepare_publish.outputs.package_version }}.tar.gz dist/
          mv -v ${{ needs.prepare_publish.outputs.package_alternate_name }}-${{ needs.prepare_publish.outputs.package_version }}-py3-none-any.whl dist/
        # yamllint enable rule:line-length
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: True
