name: Publish on FTP

on:
  workflow_call:
    inputs:
      ftp-hostname:
        required: True
        type: string
      ftp-port:
        required: True
        type: string
      ftp-username:
        required: True
        type: string
      ftp-publish-path:
        required: True
        type: string
    secrets:
      FTP_PASSWORD:
        required: True

jobs:
  publish-on-pypi:
    name: Publish on PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y curlftpfs

      - name: Install opkg-utils
        run: |
          wget https://git.yoctoproject.org/opkg-utils/snapshot/opkg-utils-0.4.5.tar.gz
          tar xzfv opkg-utils-0.4.5.tar.gz
          make -C opkg-utils-0.4.5 PREFIX=${GITHUB_WORKSPACE} install-utils

      - name: Mount FTP
        run: |
          mkdir -pv /mnt/${{ inputs.ftp-hostname }}
          sudo curlftpfs -v -o "ssl,no_verify_peer,user=${{ inputs.ftp-username }}:${{ secrets.FTPS_PASSWORD }},allow_other,rw,gid=$(id -g),uid=$(id -u)" ftp://${{ inputs.ftp-hostname }}:${{ inputs.ftp-port }} /mnt/${{ inputs.ftp-hostname }}

      - name: Publish on FTP
        run: |
          cp -pv opkg-package/* /mnt/${{ inputs.ftp-hostname }}/${{ inputs.ftp-publish-path }}

      - name: Make new repository index
        run: |
          cd /mnt/${{ inputs.ftp-hostname }}/${{ inputs.ftp-publish-path }}
          ${GITHUB_WORKSPACE}/bin/opkg-make-index -p Packages .
