name: Publish on FTP

on:
  workflow_call:
    inputs:
      ftp-hostname:
        required: True
        type: string
      ftp-port:
        required: True
        type: string
      ftp-username:
        required: True
        type: string
      ftp-publish-path:
        required: True
        type: string
      is-dev-version:
        type: string
        default: 'false'
      repo-path:
        type: string
        default: ''
    secrets:
      FTP_PASSWORD:
        required: True

jobs:
  publish-on-ftp:
    name: Publish on FTP
    runs-on: ubuntu-latest
    steps:
      - name: Check out reusable workflow repository
        uses: actions/checkout@v4
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Download files
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Publish on FTP
        run: ./reusable-workflows/.github/scripts/publish-on-ftp.sh
        env:
          IS_DEV_VERSION: ${{ inputs.is-dev-version }}
          REPO_PATH: ${{ inputs.repo-path }}
          FTP_USER: ${{ inputs.ftp-username }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOSTNAME: ${{ inputs.ftp-hostname }}
          FTP_PORT: ${{ inputs.ftp-port }}
          FTP_PUBLISH_PATH: ${{ inputs.ftp-publish-path }}
