name: Release

on:
  workflow_call:

jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{ steps.package_vars.outputs.package_name }}
      package_alternate_name: ${{ steps.package_vars.outputs.package_alternate_name }}
      package_version: ${{ steps.package_vars.outputs.package_version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set package variables
        id: package_vars
        run: |
          echo "package_name=$(python setup.py --name)" >> $GITHUB_OUTPUT
          echo "package_alternate_name=$(echo $(python setup.py --name) | sed -r 's/-/_/g')" >> $GITHUB_OUTPUT
          echo "package_version=$(python setup.py --version)" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs:
      - prepare_release
    runs-on: ubuntu-latest
    steps:
      - name: Download output files
        uses: actions/download-artifact@v3
      - name: Release output files
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.prepare_release.outputs.package_name }}-${{ needs.prepare_release.outputs.package_version }}
          # yamllint disable rule:line-length
          files: |
            ${{ github.workspace }}/*
            ${{ github.workspace }}/${{ needs.prepare_release.outputs.package_name }}-${{ needs.prepare_release.outputs.package_version }}.tar.gz
            **/${{ needs.prepare_release.outputs.package_alternate_name }}-${{ needs.prepare_release.outputs.package_version }}-py3-none-any.whl
            ${{ needs.prepare_release.outputs.package_name }}_${{ needs.prepare_release.outputs.package_version }}_aarch64.ipk
          # yamllint enable rule:line-length
          # - name: Publish package on PyPi
          #  uses: pypa/gh-action-pypi-publish@release/v1
          #  with:
          #    user: __token__
          #    password: ${{ secrets.PYPI_API_TOKEN }}
          #    packages-dir: output/dist
