name: Release

on:
  workflow_call:
    inputs:
      package-name:
        required: True
        type: string
      package-version:
        required: True
        type: string

jobs:
  release-on-github:
    name: Release on GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Download files
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.package-version }}
          files: |
            **/python-package/*
            **/binary-files/*
            **/opkg-package/*
