name: Security

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string

jobs:
  security:
    name: Audit packages
    runs-on: ubuntu-latest
    continue-on-error: True

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.latest-python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.latest-python-version }}
          cache: pip

      - name: Install requirements
        run: |
          pip install .[lint,format,audit,tests]

      - name: Audit packages
        run: pip-audit
