name: Self code analyse

on:
  workflow_dispatch:
  push:

jobs:
  code-analyse:
    name: Code analyse
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt

      - name: Lint with black
        run: |
          black --version
          black --diff --check $(git ls-files '*.py')

      - name: Lint with mypy
        run: |
          mypy --version
          mypy $(git ls-files '*.py')

      - name: Lint with ruff
        run: |
          ruff --version
          ruff $(git ls-files '*.py')

      - name: Lint with yamllint
        run: |
          yamllint --version
          yamllint $(git ls-files '*.yaml') $(git ls-files '*.yml')
