name: Unit testing

on:
  workflow_call:
    inputs:
      package-name:
        required: True
        type: string
      python-versions:
        required: True
        type: string

jobs:
  unit-testing:
    name: Unit tests using Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check out reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: superbox-dev/python-package-workflows
          path: reusable-workflows

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Run unit tests
        run: ./reusable-workflows/.github/scripts/unit-testing.sh
        env:
          PACKAGE_NAME: ${{ inputs.package-name }}

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-python-${{ matrix.python-version }}
          path: .coverage

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-python-${{ matrix.python-version }}
          path: reports/pytest.xml
          if-no-files-found: error
