name: Validate

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string

jobs:
  validate-version:
    name: Validate version
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.latest-python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.latest-python-version }}

      - name: Check tag ${{ github.ref_name }}
        run: |
          ref_name="${GITHUB_REF_NAME}"
          package_version="v$(python setup.py --version)"

          if [ "${GITHUB_REF_TYPE}" == "tag" ] && [ "${GITHUB_REF_NAME}" != "${package_version}" ]; then
            echo "Version number in package does not match tag! (${GITHUB_REF_NAME} vs. ${package_version})."
            exit 1
          fi
