name: Validate

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string

jobs:
  validate-version:
    name: Validate version
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.latest-python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.latest-python }}

      - name: Check tag ${{ github.ref_name }}
        run: |
          ref_name="${{ github.ref_name }}"
          tag_version="${ref_name/.dev/}"
          package_version="$(python setup.py --version)"

          if [ "${tag_version}" != "${package_version}" ]; then
            echo "Version number in package does not match tag! (${tag_version} vs. ${package_version})."
            exit 1
          fi
